### ISSUE TITLE
Motion Detection takes minutes to trigger

### ISSUE THREAD

**Issue by robkjr** [digitalcraig/adt-pulse-mqtt#27]
Working with some automation now that I have access to my ADT sensors and I'm finding that it takes minutes for motion sensors to go from clear to detected and from detected to clear. This is in comparison to the ADT system itself which works almost immediately.  Is there any way to fix this?

**Comment by digitalcraig** [comment]
The add-on has to scape the ADT website and it does have a delay (5 seconds) between checks to avoid being blocked for denial-of-service. There will be some delay which is unavoidable. Motion detectors are particularly difficult to deal with because it could change to detected and back to clear between updates. That's what happens with mine anyway.

However, you may want to use an app like MQTT snooper to connect directly to your mosquito to verify how long it takes for the topic to get updated by the add-on versus how long it takes for Home Assistant to pick up the change.

**Comment by robkjr** [comment]
Thanks, Craig,

I figured it may be something like this.  I was just hoping to shorten the delay.

Another quick question.  When I set up the ADT connection I used this fork of the code. haruny/adt-pulse-mqtt to install the add-on.  Should I uninstall and use your fork or is the code the same?



Thanks,
Rob

**Comment by digitalcraig** [comment]
There are no significant differences between this version and the version you installed. We've used pull requests to keep them in sync. My version focuses on running it as a standalone docker container and haruny allows for it to be used as a hassio addon.

Yes, the between syncs with the ADT portal can be reduced, but I don't think it's a good idea in case they decide to block it. ADT had announced integration with services like IFTT a few years ago, but it looks like they've abandoned that for now unfortunately.
